### ISSUE TITLE
`pallet_revive` launch tracking issue

### ISSUE THREAD

**Issue by athei** [paritytech/contract-issues#13]
This issue tracks all the open changes that we need to make to `pallet_revive` so it can YUL contracts. This is only the minimal feature set for the deployment and does not include features that need to be delivered later (JIT). It also only includes changes to the pallet and not other components.

I ordered them by urgency.

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5749
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5750
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5611
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5725
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5576
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5642
- [ ] Every host function that contains functionality that is not available in Solidity should move to a "System" pre-compile
- [ ] Make `block_number` return relay chain block number?
- [ ] Make sure the returned timestamp of `now` makes sense
- [ ] https://github.com/paritytech/polkadot-sdk/pull/5861
- [x] https://github.com/paritytech/polkadot-sdk/pull/5807
- [x] https://github.com/paritytech/polkadot-sdk/pull/5779
- [x] https://github.com/paritytech/polkadot-sdk/pull/5743
- [x] https://github.com/paritytech/polkadot-sdk/pull/5701
- [x] Reevaluate our memory calculations in our initialization check and find out if we can increase the maximum stack size
- [ ] Go through the emitted logs of `pallet_revive` to make sure they make sense
- [ ] Deactivate all syscalls which are not necessary for launch (flagging them unstable)
- [ ] https://github.com/paritytech/polkadot-sdk/issues/6157
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5621
- [ ] Nice to have: get rid of the HostFn trait since we only need to support one architecture
- [ ] Convert `terminate` to a pre-compile and disallow specifying another contract as beneficiary
- [x] Ensure we are still building with polkavm linker optimisations
- [ ] Ensure we have a tests for all host apis
- [x] Allow contract instantiation with CREATE1 semantics using account nonce of sender (both for contracts and from an extrinsic)
- [x] Fix contract address derivation to be the came as on Eth as tooling might assume those
- [x] https://github.com/paritytech/polkadot-sdk/issues/5575
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5574
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5577
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5578
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5597
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5629
- [x] https://github.com/paritytech/polkadot-sdk/pull/5675
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5683
- [ ] Remove all events except contract emitted
- [ ] Update `set_code_hash` to collect immutable data of the new code
```

**Comment by athei** [comment]
Replaced with this project board: https://github.com/orgs/paritytech/projects/29/views/1
